# Generated by Django 4.2.1 on 2023-05-13 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
