# Generated by Django 4.2.1 on 2023-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(blank=True, default='no description '),
        ),
    ]
