# Generated by Django 4.2.1 on 2023-05-16 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_question_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='downvotes',
            field=models.ManyToManyField(blank=True, default=0, related_name='downvoted_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
